pipeline:
  build:
    image: andyet/node:4
    commands:
      - npm install
      - NODE_ENV=production npm run build
  now_stage:
    image: andyet/drone-now:latest
    pull: true
    deploy_name: otalk.org
    type: static
    team: andyet
    directory: public
    when:
      event: tag
    secrets: [ now_token ]
  now_prod:
    image: andyet/drone-now:latest
    pull: true
    deploy_name: otalk.org
    type: static
    team: andyet
    alias: otalk.org
    cleanup: true
    directory: public
    when:
      event: deployment
    secrets: [ now_token ]
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]
