build:
  image: andyet/node:4
  commands:
    - npm install
    - NODE_ENV=production npm run build
publish:
  upload_stage:
    image: s3_sync:native
    when:
      branch: master
      event: push
    access_key: $$AWS_ACCESS_KEY
    secret_key: $$AWS_SECRET_KEY
    bucket: stage.otalk.org
    region: $$AWS_REGION
    acl: public-read
    source: public
    delete: true
  upload_production:
    image: s3_sync:native
    when:
      event: deployment
    access_key: $$AWS_ACCESS_KEY
    secret_key: $$AWS_SECRET_KEY
    bucket: otalk.org
    region: $$AWS_REGION
    acl: public-read
    source: public
    delete: true
notify:
  slack:
    webhook_url: $$SLACK_HOOK
    username: drone
    channel: alerts
